import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Container from './components/container'
import Header from './components/header'
import Footer from './components/footer'
import StoreProvider from './StoreProvider'

const inter = Inter({ subsets: ['latin', 'cyrillic'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <Container>
          <StoreProvider>
            <Header />
            {children}
            <Footer />
          </StoreProvider>
        </Container>
      </body>
    </html>
  )
}

export default RootLayout
